site_name: MatPly Docs
site_url: https://github.com/PythonnotJava/MatPly
theme:
  name: material
nav:
  - Home: index.md
  - Guide:
      - 指南: Guide/getting-started.md
  - API Reference:
      - Dart版本的实现 : API/Dart/index.md
      - 构造函数: API/Dart/constructor.md
      - 属性: API/Dart/properties.md
      - 方法: API/Dart/methods.md
      - 重载操作: API/Dart/operators.md
      - 全局设置: API/Dart/global_methods.md