site_name: 宿舍做饭中的设计
site_url: https://www.robot-shadow.cn/

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material

plugins:
  - search

nav:
  - Home: cookie_design.md
  - API Reference:
    - 卤鸡腿: 1.md
    - 鸡汤鸡蛋波纹面: 2.md
    - 火腿炒鸡蛋: 3.md
    - 剁椒蒜蓉阳春拌面: 4.md
    - 火腿刀削面: 5.md
    - 类似胡辣汤、豆腐脑卤汁的汤汁设计: 6.md
    - 类似胡辣汤、豆腐脑卤汁的汤汁设计——改良版: 7.md
# mkdocs build